-- Copyright (c) 2025 Casey Entzi
-- SPDX-License-Identifier: MIT

-- service.default_tax_rate was a hardcoded decimal with nothing tying it to
-- an actual tax_rate row - replace it with a reference, matching the
-- ledger_account.default_tax_rate_id / invoice_line_item.tax_rate_id
-- pattern already used elsewhere.
ALTER TABLE public.service DROP COLUMN default_tax_rate;
ALTER TABLE public.service ADD COLUMN default_tax_rate_id BIGINT REFERENCES public.tax_rate(id);
CREATE INDEX service_default_tax_rate_id_idx ON public.service(default_tax_rate_id);

-- payment.invoice_id only let a payment apply to one invoice - a single
-- deposit covering several invoices (a real, common case) didn't fit.
-- Replace it with a join table: one row per invoice a payment is applied
-- against, each with its own amount, so a payment can split across many.
ALTER TABLE public.payment DROP COLUMN invoice_id;

CREATE TABLE public.payment_application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL REFERENCES public.payment(id),
    invoice_id BIGINT NOT NULL REFERENCES public.invoice(id),
    applied_amount DECIMAL(15,2) NOT NULL CHECK (applied_amount > 0),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE UNIQUE INDEX payment_application_payment_invoice_uindex
    ON public.payment_application(payment_id, invoice_id);
CREATE INDEX payment_application_invoice_id_idx ON public.payment_application(invoice_id);
