CREATE TABLE public.business (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    tax_id VARCHAR(50),
    address_line1 VARCHAR(255),
    address_line2 VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(50),
    postal_code VARCHAR(20),
    country VARCHAR(2) DEFAULT 'US',
    phone VARCHAR(50),
    email VARCHAR(255),
    website_url VARCHAR(500),
    logo_url VARCHAR(500),
    default_payment_terms_days INTEGER DEFAULT 30,
    default_tax_rate DECIMAL(5,4) DEFAULT 0.00,
    default_invoice_terms TEXT,
    default_estimate_terms TEXT,
    invoice_number_prefix VARCHAR(10) DEFAULT 'INV',
    estimate_number_prefix VARCHAR(10) DEFAULT 'EST',
    next_invoice_number INTEGER DEFAULT 1000,
    next_estimate_number INTEGER DEFAULT 1000,
    timezone VARCHAR(50) DEFAULT 'America/New_York',
    currency_code VARCHAR(3) DEFAULT 'USD',
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX business_name_uindex
    on public.business(name);

CREATE TABLE public.ledger_account_type (
    id INTEGER PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    normal_balance VARCHAR(10) NOT NULL CHECK (normal_balance IN ('DEBIT', 'CREDIT')),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Balance-sheet placement (asset/liability/equity/revenue/expense) is already
-- derivable from ledger_account_type + normal_balance above, so no separate
-- table is needed for that. Cash-flow classification (Operating/Investing/
-- Financing) is not derivable from account_type, hence this dedicated table.
CREATE TABLE public.cash_flow_category (
    id INTEGER PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    display_sequence INTEGER DEFAULT 0 NOT NULL
);

CREATE TABLE public.ledger_account (
    id INTEGER PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    account_type_id INTEGER NOT NULL REFERENCES public.ledger_account_type(id),
    code VARCHAR(20) NOT NULL,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    parent_account_id INTEGER REFERENCES public.ledger_account(id),
    is_system BOOLEAN DEFAULT FALSE NOT NULL,
    is_reconcilable BOOLEAN DEFAULT FALSE NOT NULL,
    is_container BOOLEAN DEFAULT FALSE NOT NULL,
    display_sequence INTEGER DEFAULT 0 NOT NULL,
    default_tax_rate_id BIGINT,
    cash_flow_category_id INTEGER REFERENCES public.cash_flow_category(id),
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE UNIQUE INDEX ledger_account_business_code_uindex
    ON public.ledger_account(business_id, code);
-- Opening balances are not a column here: model them as a ledger_transaction/ledger_entry
-- pair against a system "Opening Balance Equity" account (is_system = true) instead,
-- keeping the ledger strictly double-entry with no special-cased balance field.
-- Running balances are likewise not cached on this table; compute by aggregating
-- ledger_entry per account, and revisit only if query performance demands a cache.
CREATE UNIQUE INDEX ledger_account_business_parent_name_uindex
    ON public.ledger_account(business_id, COALESCE(parent_account_id, 0), name);

CREATE TABLE public.ledger_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    transaction_date DATE NOT NULL,
    description TEXT,
    reference_number VARCHAR(100),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP
);

CREATE INDEX ledger_transaction_business_id_idx ON public.ledger_transaction(business_id);
CREATE INDEX ledger_transaction_date_idx ON public.ledger_transaction(transaction_date);

CREATE TABLE public.ledger_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    ledger_transaction_id BIGINT NOT NULL REFERENCES public.ledger_transaction(id),
    account_id INTEGER NOT NULL REFERENCES public.ledger_account(id),
    debit_amount DECIMAL(15,2) DEFAULT 0.00 NOT NULL CHECK (debit_amount >= 0),
    credit_amount DECIMAL(15,2) DEFAULT 0.00 NOT NULL CHECK (credit_amount >= 0),
    description TEXT,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT ledger_entry_debit_or_credit CHECK (
        (debit_amount > 0 AND credit_amount = 0) OR
        (credit_amount > 0 AND debit_amount = 0)
    )
);

CREATE INDEX ledger_entry_business_id_idx ON public.ledger_entry(business_id);
CREATE INDEX ledger_entry_ledger_transaction_id_idx ON public.ledger_entry(ledger_transaction_id);
CREATE INDEX ledger_entry_account_id_idx ON public.ledger_entry(account_id);

CREATE TABLE public.bank_statement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    ledger_account_id INTEGER NOT NULL REFERENCES public.ledger_account(id),
    statement_name VARCHAR(200) NOT NULL,
    statement_date DATE NOT NULL,
    opening_balance DECIMAL(15,2),
    closing_balance DECIMAL(15,2),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP
);

CREATE INDEX bank_statement_business_id_idx ON public.bank_statement(business_id);
CREATE INDEX bank_statement_ledger_account_id_idx ON public.bank_statement(ledger_account_id);
CREATE INDEX bank_statement_date_idx ON public.bank_statement(statement_date);

CREATE TABLE public.bank_statement_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_statement_id BIGINT NOT NULL REFERENCES public.bank_statement(id),
    ledger_transaction_id BIGINT NOT NULL REFERENCES public.ledger_transaction(id),
    display_sequence INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE UNIQUE INDEX bank_statement_line_statement_transaction_uindex
    ON public.bank_statement_line(bank_statement_id, ledger_transaction_id);
CREATE INDEX bank_statement_line_ledger_transaction_id_idx ON public.bank_statement_line(ledger_transaction_id);

CREATE TABLE public.tax_rate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    name VARCHAR(100) NOT NULL,
    rate DECIMAL(5,4) NOT NULL,
    tax_liability_account_id INTEGER NOT NULL REFERENCES public.ledger_account(id),
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE UNIQUE INDEX tax_rate_business_name_uindex ON public.tax_rate(business_id, name);
CREATE INDEX tax_rate_tax_liability_account_id_idx ON public.tax_rate(tax_liability_account_id);

-- Deferred FK: ledger_account.default_tax_rate_id points at tax_rate, which is
-- declared after ledger_account, so the constraint is added here instead of inline.
ALTER TABLE public.ledger_account
    ADD CONSTRAINT ledger_account_default_tax_rate_id_fkey
    FOREIGN KEY (default_tax_rate_id) REFERENCES public.tax_rate(id);
CREATE INDEX ledger_account_default_tax_rate_id_idx ON public.ledger_account(default_tax_rate_id);
CREATE INDEX ledger_account_cash_flow_category_id_idx ON public.ledger_account(cash_flow_category_id);

-- Generic party record, reusable for both accounts receivable (customers) and
-- accounts payable (vendors) - a party can be either or both, hence the two
-- independent flags rather than a single type enum.
-- estimate.customer_id still keeps its AR-specific name (estimates are
-- inherently a sales-side document, see the estimate table below). invoice
-- and payment generalized to contact_id since both can now represent either
-- AR or AP activity (see invoice.invoice_type / payment.payment_type).
CREATE TABLE public.contact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    ledger_account_id INTEGER REFERENCES public.ledger_account(id),
    contact_number VARCHAR(50) NOT NULL,
    is_customer BOOLEAN DEFAULT TRUE NOT NULL,
    is_vendor BOOLEAN DEFAULT FALSE NOT NULL,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    billing_address_line1 VARCHAR(255),
    billing_address_line2 VARCHAR(255),
    billing_city VARCHAR(100),
    billing_state VARCHAR(50),
    billing_postal_code VARCHAR(20),
    billing_country VARCHAR(2) DEFAULT 'US',
    shipping_address_line1 VARCHAR(255),
    shipping_address_line2 VARCHAR(255),
    shipping_city VARCHAR(100),
    shipping_state VARCHAR(50),
    shipping_postal_code VARCHAR(20),
    shipping_country VARCHAR(2) DEFAULT 'US',
    payment_terms_days INTEGER DEFAULT 30,
    credit_limit DECIMAL(15,2),
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX contact_business_number_uindex
    ON public.contact(business_id, contact_number);
CREATE INDEX contact_ledger_account_id_idx ON public.contact(ledger_account_id);

CREATE TABLE public.service (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    service_code VARCHAR(50) NOT NULL,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    unit_of_measure VARCHAR(20) DEFAULT 'EACH',
    cost_price DECIMAL(15,2) DEFAULT 0.00,
    retail_price DECIMAL(15,2) NOT NULL,
    is_taxable BOOLEAN DEFAULT FALSE NOT NULL,
    default_tax_rate DECIMAL(5,4) DEFAULT 0.00,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX service_business_code_uindex
    ON public.service(business_id, service_code);
CREATE INDEX service_business_active_idx ON public.service(business_id, is_active);

CREATE TABLE public.estimate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    customer_id BIGINT NOT NULL REFERENCES public.contact(id),
    estimate_number VARCHAR(50) NOT NULL,
    estimate_date DATE NOT NULL,
    expiration_date DATE NOT NULL,
    subtotal DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    total_tax_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    discount_amount DECIMAL(15,2) DEFAULT 0.00,
    total_amount DECIMAL(15,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'SENT', 'ACCEPTED', 'DECLINED', 'EXPIRED')),
    notes TEXT,
    terms TEXT,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX estimate_business_number_uindex
    ON public.estimate(business_id, estimate_number);
CREATE INDEX estimate_customer_id_idx ON public.estimate(customer_id);
CREATE INDEX estimate_status_idx ON public.estimate(status);
CREATE INDEX estimate_expiration_date_idx ON public.estimate(expiration_date);

CREATE TABLE public.estimate_line_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estimate_id BIGINT NOT NULL REFERENCES public.estimate(id),
    service_id BIGINT REFERENCES public.service(id),
    line_number INTEGER NOT NULL,
    description TEXT NOT NULL,
    quantity DECIMAL(15,4) NOT NULL DEFAULT 1.0000,
    unit_price DECIMAL(15,2) NOT NULL,
    line_subtotal DECIMAL(15,2) NOT NULL,
    is_taxable BOOLEAN DEFAULT FALSE NOT NULL,
    tax_rate_id BIGINT REFERENCES public.tax_rate(id),
    tax_rate DECIMAL(5,4) DEFAULT 0.00,
    tax_amount DECIMAL(15,2) DEFAULT 0.00 NOT NULL,
    line_total DECIMAL(15,2) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP
);

CREATE INDEX estimate_line_item_estimate_id_idx ON public.estimate_line_item(estimate_id);
CREATE INDEX estimate_line_item_service_id_idx ON public.estimate_line_item(service_id);
CREATE INDEX estimate_line_item_tax_rate_id_idx ON public.estimate_line_item(tax_rate_id);

-- invoice_type distinguishes accounts-receivable (SALES: sent to a customer)
-- from accounts-payable (PURCHASE: a vendor bill received) documents, sharing
-- one table/shape rather than splitting into a separate bill/bill_line_item
-- pair - similar to the Odoo account.move/move_type pattern. contact_id references either a
-- customer or vendor contact depending on invoice_type (see
-- contact.is_customer/is_vendor); invoice_number for a PURCHASE row is
-- typically the vendor's own document number, not one we generate.
CREATE TABLE public.invoice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    contact_id BIGINT NOT NULL REFERENCES public.contact(id),
    invoice_type VARCHAR(20) NOT NULL DEFAULT 'SALES' CHECK (invoice_type IN ('SALES', 'PURCHASE')),
    estimate_id BIGINT REFERENCES public.estimate(id),
    invoice_number VARCHAR(50) NOT NULL,
    invoice_date DATE NOT NULL,
    due_date DATE NOT NULL,
    subtotal DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    total_tax_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    discount_amount DECIMAL(15,2) DEFAULT 0.00,
    total_amount DECIMAL(15,2) NOT NULL,
    paid_amount DECIMAL(15,2) DEFAULT 0.00,
    balance_due DECIMAL(15,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'SENT', 'PAID', 'OVERDUE', 'CANCELLED')),
    notes TEXT,
    terms TEXT,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX invoice_business_number_uindex
    ON public.invoice(business_id, invoice_number);
CREATE INDEX invoice_contact_id_idx ON public.invoice(contact_id);
CREATE INDEX invoice_estimate_id_idx ON public.invoice(estimate_id);
CREATE INDEX invoice_status_idx ON public.invoice(status);
CREATE INDEX invoice_due_date_idx ON public.invoice(due_date);
CREATE INDEX invoice_type_idx ON public.invoice(invoice_type);

CREATE TABLE public.invoice_line_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES public.invoice(id),
    service_id BIGINT REFERENCES public.service(id),
    line_number INTEGER NOT NULL,
    description TEXT NOT NULL,
    quantity DECIMAL(15,4) NOT NULL DEFAULT 1.0000,
    unit_price DECIMAL(15,2) NOT NULL,
    line_subtotal DECIMAL(15,2) NOT NULL,
    is_taxable BOOLEAN DEFAULT FALSE NOT NULL,
    tax_rate_id BIGINT REFERENCES public.tax_rate(id),
    tax_rate DECIMAL(5,4) DEFAULT 0.00,
    tax_amount DECIMAL(15,2) DEFAULT 0.00 NOT NULL,
    line_total DECIMAL(15,2) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP
);

CREATE INDEX invoice_line_item_invoice_id_idx ON public.invoice_line_item(invoice_id);
CREATE INDEX invoice_line_item_service_id_idx ON public.invoice_line_item(service_id);
CREATE INDEX invoice_line_item_tax_rate_id_idx ON public.invoice_line_item(tax_rate_id);

-- payment_type carries direction (money received from a customer vs money we
-- paid to a vendor) independent of invoice_id, since invoice_id is nullable
-- (a deposit/retainer/on-account payment may exist with no linked invoice, so
-- direction can't always be inferred by joining through to invoice.invoice_type).
CREATE TABLE public.payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    contact_id BIGINT NOT NULL REFERENCES public.contact(id),
    invoice_id BIGINT REFERENCES public.invoice(id),
    payment_type VARCHAR(20) NOT NULL DEFAULT 'RECEIVED' CHECK (payment_type IN ('RECEIVED', 'MADE')),
    payment_number VARCHAR(50) NOT NULL,
    payment_date DATE NOT NULL,
    amount DECIMAL(15,2) NOT NULL CHECK (amount > 0),
    payment_method VARCHAR(20) NOT NULL CHECK (payment_method IN ('CASH', 'CHECK', 'CREDIT_CARD', 'ACH', 'WIRE', 'OTHER')),
    reference_number VARCHAR(100),
    notes TEXT,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX payment_business_number_uindex
    ON public.payment(business_id, payment_number);
CREATE INDEX payment_contact_id_idx ON public.payment(contact_id);
CREATE INDEX payment_invoice_id_idx ON public.payment(invoice_id);
CREATE INDEX payment_date_idx ON public.payment(payment_date);
CREATE INDEX payment_type_idx ON public.payment(payment_type);

-- Polymorphic store for AI-generated context (summaries, categorization hints,
-- anomaly flags, user notes) tied to any entity (customer, ledger_transaction,
-- ledger_account, invoice, ...), so a future Claude Code session (via the MCP
-- server) can retrieve prior context about an entity it's working on. No FK on
-- entity_id since it spans multiple target tables. `source`/`metadata` can
-- carry an MCP session/conversation identifier without needing dedicated
-- columns for it.
--
-- Append-only by convention: rows are never edited in place. As granular
-- context accumulates for an entity, a batch of old rows can be rolled up
-- into a single new row (typically context_type = 'summary') with
-- superseded_by_id set on the old rows pointing at it, so retrieval can
-- default to `WHERE superseded_by_id IS NULL` (current context only) while
-- the full trail remains queryable for audit. Genuinely low-value or expired
-- rows are pruned via the existing deleted_at soft-delete; retention policy
-- (what/when to prune) is an application/job concern, not schema.
CREATE TABLE public.entity_context (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    entity_type VARCHAR(50) NOT NULL,
    entity_id BIGINT NOT NULL,
    context_type VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    metadata JSONB,
    source VARCHAR(100),
    confidence DECIMAL(5,4),
    superseded_by_id BIGINT REFERENCES public.entity_context(id),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP
);

CREATE INDEX entity_context_entity_idx ON public.entity_context(entity_type, entity_id);
CREATE INDEX entity_context_business_id_idx ON public.entity_context(business_id);
CREATE INDEX entity_context_superseded_by_id_idx ON public.entity_context(superseded_by_id);

-- Same polymorphic entity_type/entity_id pattern as entity_context above, for
-- files attached to any entity (receipts, contracts, logos, ...).
CREATE TABLE public.attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    entity_type VARCHAR(50) NOT NULL,
    entity_id BIGINT NOT NULL,
    original_filename VARCHAR(500),
    storage_url VARCHAR(1000) NOT NULL,
    content_type VARCHAR(100),
    file_size_bytes BIGINT,
    display_sequence INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP
);

CREATE INDEX attachment_entity_idx ON public.attachment(entity_type, entity_id);
CREATE INDEX attachment_business_id_idx ON public.attachment(business_id);

INSERT INTO public.ledger_account_type (id, name, description, normal_balance) VALUES
(1, 'ASSETS', 'Economic resources owned by the company', 'DEBIT'),
(2, 'LIABILITIES', 'Debts and obligations owed by the company', 'CREDIT'),
(3, 'EQUITY', 'Ownership interest in the company', 'CREDIT'),
(4, 'REVENUE', 'Income earned from business operations', 'CREDIT'),
(5, 'EXPENSES', 'Costs incurred in business operations', 'DEBIT'),
(6, 'TAX_LIABILITY', 'Taxes collected on behalf of government agencies', 'CREDIT');

INSERT INTO public.cash_flow_category (id, name, display_sequence) VALUES
(1, 'Operating', 1),
(2, 'Investing', 2),
(3, 'Financing', 3);
