// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppUser = `-- name: CreateAppUser :one
INSERT INTO app_user (email, display_name)
VALUES ($1, $2)
RETURNING id, email, display_name, is_active, created_at, updated_at, deleted_at
`

type CreateAppUserParams struct {
	Email       string  `json:"email"`
	DisplayName *string `json:"display_name"`
}

func (q *Queries) CreateAppUser(ctx context.Context, arg CreateAppUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, createAppUser, arg.Email, arg.DisplayName)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createBusinessUser = `-- name: CreateBusinessUser :one
INSERT INTO business_user (business_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, business_id, user_id, role, created_at, updated_at
`

type CreateBusinessUserParams struct {
	BusinessID int64  `json:"business_id"`
	UserID     int64  `json:"user_id"`
	Role       string `json:"role"`
}

func (q *Queries) CreateBusinessUser(ctx context.Context, arg CreateBusinessUserParams) (BusinessUser, error) {
	row := q.db.QueryRow(ctx, createBusinessUser, arg.BusinessID, arg.UserID, arg.Role)
	var i BusinessUser
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO user_session (user_id, refresh_token_hash, client_name, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, refresh_token_hash, client_name, issued_at, expires_at, last_used_at, revoked_at, replaced_by_session_id
`

type CreateUserSessionParams struct {
	UserID           int64            `json:"user_id"`
	RefreshTokenHash string           `json:"refresh_token_hash"`
	ClientName       *string          `json:"client_name"`
	ExpiresAt        pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createUserSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.ClientName,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ClientName,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.ReplacedBySessionID,
	)
	return i, err
}

const createWebAuthnCredential = `-- name: CreateWebAuthnCredential :one
INSERT INTO webauthn_credential (
    user_id, credential_id, public_key, attestation_type, transports,
    aaguid, sign_count, name
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, credential_id, public_key, attestation_type, transports, aaguid, sign_count, name, created_at, last_used_at
`

type CreateWebAuthnCredentialParams struct {
	UserID          int64   `json:"user_id"`
	CredentialID    []byte  `json:"credential_id"`
	PublicKey       []byte  `json:"public_key"`
	AttestationType *string `json:"attestation_type"`
	Transports      *string `json:"transports"`
	Aaguid          []byte  `json:"aaguid"`
	SignCount       int64   `json:"sign_count"`
	Name            *string `json:"name"`
}

func (q *Queries) CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, createWebAuthnCredential,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.AttestationType,
		arg.Transports,
		arg.Aaguid,
		arg.SignCount,
		arg.Name,
	)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Transports,
		&i.Aaguid,
		&i.SignCount,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getAppUser = `-- name: GetAppUser :one
SELECT id, email, display_name, is_active, created_at, updated_at, deleted_at FROM app_user WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAppUser(ctx context.Context, id int64) (AppUser, error) {
	row := q.db.QueryRow(ctx, getAppUser, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAppUserByEmail = `-- name: GetAppUserByEmail :one
SELECT id, email, display_name, is_active, created_at, updated_at, deleted_at FROM app_user WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAppUserByEmail(ctx context.Context, email string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getAppUserByEmail, email)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBusinessUser = `-- name: GetBusinessUser :one
SELECT id, business_id, user_id, role, created_at, updated_at FROM business_user WHERE business_id = $1 AND user_id = $2
`

type GetBusinessUserParams struct {
	BusinessID int64 `json:"business_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) GetBusinessUser(ctx context.Context, arg GetBusinessUserParams) (BusinessUser, error) {
	row := q.db.QueryRow(ctx, getBusinessUser, arg.BusinessID, arg.UserID)
	var i BusinessUser
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSessionByHash = `-- name: GetUserSessionByHash :one
SELECT id, user_id, refresh_token_hash, client_name, issued_at, expires_at, last_used_at, revoked_at, replaced_by_session_id FROM user_session
WHERE refresh_token_hash = $1 AND revoked_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetUserSessionByHash(ctx context.Context, refreshTokenHash string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSessionByHash, refreshTokenHash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ClientName,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.ReplacedBySessionID,
	)
	return i, err
}

const getWebAuthnCredentialByCredentialID = `-- name: GetWebAuthnCredentialByCredentialID :one
SELECT id, user_id, credential_id, public_key, attestation_type, transports, aaguid, sign_count, name, created_at, last_used_at FROM webauthn_credential WHERE credential_id = $1
`

func (q *Queries) GetWebAuthnCredentialByCredentialID(ctx context.Context, credentialID []byte) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, getWebAuthnCredentialByCredentialID, credentialID)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Transports,
		&i.Aaguid,
		&i.SignCount,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listWebAuthnCredentialsForUser = `-- name: ListWebAuthnCredentialsForUser :many
SELECT id, user_id, credential_id, public_key, attestation_type, transports, aaguid, sign_count, name, created_at, last_used_at FROM webauthn_credential WHERE user_id = $1 ORDER BY id
`

func (q *Queries) ListWebAuthnCredentialsForUser(ctx context.Context, userID int64) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, listWebAuthnCredentialsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebauthnCredential
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.AttestationType,
			&i.Transports,
			&i.Aaguid,
			&i.SignCount,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserSession = `-- name: RevokeUserSession :one
UPDATE user_session SET revoked_at = NOW(), replaced_by_session_id = $1
WHERE id = $2 AND revoked_at IS NULL
RETURNING id, user_id, refresh_token_hash, client_name, issued_at, expires_at, last_used_at, revoked_at, replaced_by_session_id
`

type RevokeUserSessionParams struct {
	ReplacedBySessionID *int64 `json:"replaced_by_session_id"`
	ID                  int64  `json:"id"`
}

func (q *Queries) RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, revokeUserSession, arg.ReplacedBySessionID, arg.ID)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ClientName,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.ReplacedBySessionID,
	)
	return i, err
}

const updateWebAuthnCredentialSignCount = `-- name: UpdateWebAuthnCredentialSignCount :exec
UPDATE webauthn_credential SET sign_count = $2, last_used_at = NOW() WHERE id = $1
`

type UpdateWebAuthnCredentialSignCountParams struct {
	ID        int64 `json:"id"`
	SignCount int64 `json:"sign_count"`
}

func (q *Queries) UpdateWebAuthnCredentialSignCount(ctx context.Context, arg UpdateWebAuthnCredentialSignCountParams) error {
	_, err := q.db.Exec(ctx, updateWebAuthnCredentialSignCount, arg.ID, arg.SignCount)
	return err
}
