// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: banking.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBankStatement = `-- name: CreateBankStatement :one

INSERT INTO bank_statement (
    business_id, ledger_account_id, statement_name, statement_date,
    opening_balance, closing_balance, created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, business_id, ledger_account_id, statement_name, statement_date, opening_balance, closing_balance, created_by_user_id, created_at, updated_at, deleted_at
`

type CreateBankStatementParams struct {
	BusinessID      int64          `json:"business_id"`
	LedgerAccountID int32          `json:"ledger_account_id"`
	StatementName   string         `json:"statement_name"`
	StatementDate   pgtype.Date    `json:"statement_date"`
	OpeningBalance  pgtype.Numeric `json:"opening_balance"`
	ClosingBalance  pgtype.Numeric `json:"closing_balance"`
	CreatedByUserID *int64         `json:"created_by_user_id"`
}

// Copyright (c) 2025 Casey Entzi
// SPDX-License-Identifier: MIT
func (q *Queries) CreateBankStatement(ctx context.Context, arg CreateBankStatementParams) (BankStatement, error) {
	row := q.db.QueryRow(ctx, createBankStatement,
		arg.BusinessID,
		arg.LedgerAccountID,
		arg.StatementName,
		arg.StatementDate,
		arg.OpeningBalance,
		arg.ClosingBalance,
		arg.CreatedByUserID,
	)
	var i BankStatement
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LedgerAccountID,
		&i.StatementName,
		&i.StatementDate,
		&i.OpeningBalance,
		&i.ClosingBalance,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createBankStatementLine = `-- name: CreateBankStatementLine :one
INSERT INTO bank_statement_line (bank_statement_id, ledger_transaction_id, display_sequence)
VALUES ($1, $2, $3)
RETURNING id, bank_statement_id, ledger_transaction_id, display_sequence, created_at
`

type CreateBankStatementLineParams struct {
	BankStatementID     int64 `json:"bank_statement_id"`
	LedgerTransactionID int64 `json:"ledger_transaction_id"`
	DisplaySequence     int32 `json:"display_sequence"`
}

func (q *Queries) CreateBankStatementLine(ctx context.Context, arg CreateBankStatementLineParams) (BankStatementLine, error) {
	row := q.db.QueryRow(ctx, createBankStatementLine, arg.BankStatementID, arg.LedgerTransactionID, arg.DisplaySequence)
	var i BankStatementLine
	err := row.Scan(
		&i.ID,
		&i.BankStatementID,
		&i.LedgerTransactionID,
		&i.DisplaySequence,
		&i.CreatedAt,
	)
	return i, err
}

const getBankStatement = `-- name: GetBankStatement :one
SELECT id, business_id, ledger_account_id, statement_name, statement_date, opening_balance, closing_balance, created_by_user_id, created_at, updated_at, deleted_at FROM bank_statement WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBankStatement(ctx context.Context, id int64) (BankStatement, error) {
	row := q.db.QueryRow(ctx, getBankStatement, id)
	var i BankStatement
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LedgerAccountID,
		&i.StatementName,
		&i.StatementDate,
		&i.OpeningBalance,
		&i.ClosingBalance,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const ledgerEntryExistsForAccount = `-- name: LedgerEntryExistsForAccount :one
SELECT EXISTS(
    SELECT 1 FROM ledger_entry
    WHERE ledger_transaction_id = $1
        AND account_id = $2
        AND deleted_at IS NULL
) AS entry_exists
`

type LedgerEntryExistsForAccountParams struct {
	LedgerTransactionID int64 `json:"ledger_transaction_id"`
	AccountID           int32 `json:"account_id"`
}

func (q *Queries) LedgerEntryExistsForAccount(ctx context.Context, arg LedgerEntryExistsForAccountParams) (bool, error) {
	row := q.db.QueryRow(ctx, ledgerEntryExistsForAccount, arg.LedgerTransactionID, arg.AccountID)
	var entry_exists bool
	err := row.Scan(&entry_exists)
	return entry_exists, err
}

const listBankStatementLines = `-- name: ListBankStatementLines :many
SELECT id, bank_statement_id, ledger_transaction_id, display_sequence, created_at FROM bank_statement_line WHERE bank_statement_id = $1 ORDER BY display_sequence, id
`

func (q *Queries) ListBankStatementLines(ctx context.Context, bankStatementID int64) ([]BankStatementLine, error) {
	rows, err := q.db.Query(ctx, listBankStatementLines, bankStatementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankStatementLine
	for rows.Next() {
		var i BankStatementLine
		if err := rows.Scan(
			&i.ID,
			&i.BankStatementID,
			&i.LedgerTransactionID,
			&i.DisplaySequence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankStatements = `-- name: ListBankStatements :many
SELECT id, business_id, ledger_account_id, statement_name, statement_date, opening_balance, closing_balance, created_by_user_id, created_at, updated_at, deleted_at FROM bank_statement WHERE business_id = $1 AND deleted_at IS NULL ORDER BY statement_date DESC
`

func (q *Queries) ListBankStatements(ctx context.Context, businessID int64) ([]BankStatement, error) {
	rows, err := q.db.Query(ctx, listBankStatements, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankStatement
	for rows.Next() {
		var i BankStatement
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.LedgerAccountID,
			&i.StatementName,
			&i.StatementDate,
			&i.OpeningBalance,
			&i.ClosingBalance,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreconciledLedgerTransactions = `-- name: ListUnreconciledLedgerTransactions :many
SELECT DISTINCT lt.id, lt.business_id, lt.transaction_date, lt.description, lt.reference_number, lt.created_by_user_id, lt.created_at, lt.updated_at, lt.deleted_at
FROM ledger_transaction lt
JOIN ledger_entry le ON le.ledger_transaction_id = lt.id AND le.deleted_at IS NULL
WHERE le.account_id = $1
    AND lt.deleted_at IS NULL
    AND lt.transaction_date <= $2
    AND NOT EXISTS (
        SELECT 1 FROM bank_statement_line bsl
        JOIN bank_statement bs ON bs.id = bsl.bank_statement_id
        WHERE bsl.ledger_transaction_id = lt.id AND bs.ledger_account_id = $1
    )
ORDER BY lt.transaction_date
`

type ListUnreconciledLedgerTransactionsParams struct {
	AccountID   int32       `json:"account_id"`
	ThroughDate pgtype.Date `json:"through_date"`
}

// ledger_transaction rows touching account_id, through_date, that have no
// bank_statement_line yet under any bank_statement for THIS account
// (reconciliation is scoped per-account: a transaction reconciled on one
// side of a transfer isn't automatically reconciled on the other).
func (q *Queries) ListUnreconciledLedgerTransactions(ctx context.Context, arg ListUnreconciledLedgerTransactionsParams) ([]LedgerTransaction, error) {
	rows, err := q.db.Query(ctx, listUnreconciledLedgerTransactions, arg.AccountID, arg.ThroughDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerTransaction
	for rows.Next() {
		var i LedgerTransaction
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.TransactionDate,
			&i.Description,
			&i.ReferenceNumber,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumReconciledActivity = `-- name: SumReconciledActivity :one
SELECT
    COALESCE(SUM(le.debit_amount), 0)::numeric AS total_debit,
    COALESCE(SUM(le.credit_amount), 0)::numeric AS total_credit
FROM bank_statement_line bsl
JOIN ledger_entry le ON le.ledger_transaction_id = bsl.ledger_transaction_id
    AND le.account_id = $1
    AND le.deleted_at IS NULL
WHERE bsl.bank_statement_id = $2
`

type SumReconciledActivityParams struct {
	AccountID       int32 `json:"account_id"`
	BankStatementID int64 `json:"bank_statement_id"`
}

type SumReconciledActivityRow struct {
	TotalDebit  pgtype.Numeric `json:"total_debit"`
	TotalCredit pgtype.Numeric `json:"total_credit"`
}

// Total debit/credit, for one account, across every ledger_transaction
// already reconciled (linked via bank_statement_line) to one bank_statement.
func (q *Queries) SumReconciledActivity(ctx context.Context, arg SumReconciledActivityParams) (SumReconciledActivityRow, error) {
	row := q.db.QueryRow(ctx, sumReconciledActivity, arg.AccountID, arg.BankStatementID)
	var i SumReconciledActivityRow
	err := row.Scan(&i.TotalDebit, &i.TotalCredit)
	return i, err
}
