// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerAccount = `-- name: CreateLedgerAccount :one

INSERT INTO ledger_account (
    business_id, account_type_id, code, name, description,
    is_system, is_reconcilable, cash_flow_category_id,
    balance_sheet_category_id, income_statement_category_id, created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, business_id, account_type_id, code, name, description, is_system, is_reconcilable, display_sequence, cash_flow_category_id, balance_sheet_category_id, income_statement_category_id, is_active, created_by_user_id, created_at, updated_at
`

type CreateLedgerAccountParams struct {
	BusinessID                int64   `json:"business_id"`
	AccountTypeID             int32   `json:"account_type_id"`
	Code                      string  `json:"code"`
	Name                      string  `json:"name"`
	Description               *string `json:"description"`
	IsSystem                  bool    `json:"is_system"`
	IsReconcilable            bool    `json:"is_reconcilable"`
	CashFlowCategoryID        *int32  `json:"cash_flow_category_id"`
	BalanceSheetCategoryID    *int32  `json:"balance_sheet_category_id"`
	IncomeStatementCategoryID *int32  `json:"income_statement_category_id"`
	CreatedByUserID           *int64  `json:"created_by_user_id"`
}

// Copyright (c) 2025 Casey Entzi
// SPDX-License-Identifier: MIT
func (q *Queries) CreateLedgerAccount(ctx context.Context, arg CreateLedgerAccountParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, createLedgerAccount,
		arg.BusinessID,
		arg.AccountTypeID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.IsSystem,
		arg.IsReconcilable,
		arg.CashFlowCategoryID,
		arg.BalanceSheetCategoryID,
		arg.IncomeStatementCategoryID,
		arg.CreatedByUserID,
	)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.AccountTypeID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.IsReconcilable,
		&i.DisplaySequence,
		&i.CashFlowCategoryID,
		&i.BalanceSheetCategoryID,
		&i.IncomeStatementCategoryID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger_entry (
    business_id, ledger_transaction_id, account_id, debit_amount, credit_amount, description
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, business_id, ledger_transaction_id, account_id, debit_amount, credit_amount, description, created_at, updated_at, deleted_at
`

type CreateLedgerEntryParams struct {
	BusinessID          int64          `json:"business_id"`
	LedgerTransactionID int64          `json:"ledger_transaction_id"`
	AccountID           int32          `json:"account_id"`
	DebitAmount         pgtype.Numeric `json:"debit_amount"`
	CreditAmount        pgtype.Numeric `json:"credit_amount"`
	Description         *string        `json:"description"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.BusinessID,
		arg.LedgerTransactionID,
		arg.AccountID,
		arg.DebitAmount,
		arg.CreditAmount,
		arg.Description,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LedgerTransactionID,
		&i.AccountID,
		&i.DebitAmount,
		&i.CreditAmount,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createLedgerTransaction = `-- name: CreateLedgerTransaction :one
INSERT INTO ledger_transaction (
    business_id, transaction_date, description, reference_number, created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, business_id, transaction_date, description, reference_number, created_by_user_id, created_at, updated_at, deleted_at
`

type CreateLedgerTransactionParams struct {
	BusinessID      int64       `json:"business_id"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	Description     *string     `json:"description"`
	ReferenceNumber *string     `json:"reference_number"`
	CreatedByUserID *int64      `json:"created_by_user_id"`
}

func (q *Queries) CreateLedgerTransaction(ctx context.Context, arg CreateLedgerTransactionParams) (LedgerTransaction, error) {
	row := q.db.QueryRow(ctx, createLedgerTransaction,
		arg.BusinessID,
		arg.TransactionDate,
		arg.Description,
		arg.ReferenceNumber,
		arg.CreatedByUserID,
	)
	var i LedgerTransaction
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.TransactionDate,
		&i.Description,
		&i.ReferenceNumber,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deactivateLedgerAccount = `-- name: DeactivateLedgerAccount :one
UPDATE ledger_account SET is_active = FALSE, updated_at = NOW()
WHERE id = $1
RETURNING id, business_id, account_type_id, code, name, description, is_system, is_reconcilable, display_sequence, cash_flow_category_id, balance_sheet_category_id, income_statement_category_id, is_active, created_by_user_id, created_at, updated_at
`

func (q *Queries) DeactivateLedgerAccount(ctx context.Context, id int32) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, deactivateLedgerAccount, id)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.AccountTypeID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.IsReconcilable,
		&i.DisplaySequence,
		&i.CashFlowCategoryID,
		&i.BalanceSheetCategoryID,
		&i.IncomeStatementCategoryID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLedgerAccount = `-- name: GetLedgerAccount :one
SELECT id, business_id, account_type_id, code, name, description, is_system, is_reconcilable, display_sequence, cash_flow_category_id, balance_sheet_category_id, income_statement_category_id, is_active, created_by_user_id, created_at, updated_at FROM ledger_account WHERE id = $1
`

func (q *Queries) GetLedgerAccount(ctx context.Context, id int32) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getLedgerAccount, id)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.AccountTypeID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.IsReconcilable,
		&i.DisplaySequence,
		&i.CashFlowCategoryID,
		&i.BalanceSheetCategoryID,
		&i.IncomeStatementCategoryID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLedgerAccountByCode = `-- name: GetLedgerAccountByCode :one
SELECT id, business_id, account_type_id, code, name, description, is_system, is_reconcilable, display_sequence, cash_flow_category_id, balance_sheet_category_id, income_statement_category_id, is_active, created_by_user_id, created_at, updated_at FROM ledger_account WHERE business_id = $1 AND code = $2
`

type GetLedgerAccountByCodeParams struct {
	BusinessID int64  `json:"business_id"`
	Code       string `json:"code"`
}

func (q *Queries) GetLedgerAccountByCode(ctx context.Context, arg GetLedgerAccountByCodeParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getLedgerAccountByCode, arg.BusinessID, arg.Code)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.AccountTypeID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.IsReconcilable,
		&i.DisplaySequence,
		&i.CashFlowCategoryID,
		&i.BalanceSheetCategoryID,
		&i.IncomeStatementCategoryID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLedgerAccountType = `-- name: GetLedgerAccountType :one
SELECT id, name, description, normal_balance, created_at, updated_at FROM ledger_account_type WHERE id = $1
`

func (q *Queries) GetLedgerAccountType(ctx context.Context, id int32) (LedgerAccountType, error) {
	row := q.db.QueryRow(ctx, getLedgerAccountType, id)
	var i LedgerAccountType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.NormalBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLedgerTransaction = `-- name: GetLedgerTransaction :one
SELECT id, business_id, transaction_date, description, reference_number, created_by_user_id, created_at, updated_at, deleted_at FROM ledger_transaction WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLedgerTransaction(ctx context.Context, id int64) (LedgerTransaction, error) {
	row := q.db.QueryRow(ctx, getLedgerTransaction, id)
	var i LedgerTransaction
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.TransactionDate,
		&i.Description,
		&i.ReferenceNumber,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listLedgerAccounts = `-- name: ListLedgerAccounts :many
SELECT id, business_id, account_type_id, code, name, description, is_system, is_reconcilable, display_sequence, cash_flow_category_id, balance_sheet_category_id, income_statement_category_id, is_active, created_by_user_id, created_at, updated_at FROM ledger_account WHERE business_id = $1 ORDER BY code
`

func (q *Queries) ListLedgerAccounts(ctx context.Context, businessID int64) ([]LedgerAccount, error) {
	rows, err := q.db.Query(ctx, listLedgerAccounts, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerAccount
	for rows.Next() {
		var i LedgerAccount
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.AccountTypeID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.IsReconcilable,
			&i.DisplaySequence,
			&i.CashFlowCategoryID,
			&i.BalanceSheetCategoryID,
			&i.IncomeStatementCategoryID,
			&i.IsActive,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByTransaction = `-- name: ListLedgerEntriesByTransaction :many
SELECT id, business_id, ledger_transaction_id, account_id, debit_amount, credit_amount, description, created_at, updated_at, deleted_at FROM ledger_entry WHERE ledger_transaction_id = $1 AND deleted_at IS NULL ORDER BY id
`

func (q *Queries) ListLedgerEntriesByTransaction(ctx context.Context, ledgerTransactionID int64) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByTransaction, ledgerTransactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.LedgerTransactionID,
			&i.AccountID,
			&i.DebitAmount,
			&i.CreditAmount,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByTransactionIDs = `-- name: ListLedgerEntriesByTransactionIDs :many
SELECT id, business_id, ledger_transaction_id, account_id, debit_amount, credit_amount, description, created_at, updated_at, deleted_at FROM ledger_entry WHERE ledger_transaction_id = ANY($1::bigint[]) AND deleted_at IS NULL ORDER BY id
`

func (q *Queries) ListLedgerEntriesByTransactionIDs(ctx context.Context, transactionIds []int64) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByTransactionIDs, transactionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.LedgerTransactionID,
			&i.AccountID,
			&i.DebitAmount,
			&i.CreditAmount,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerTransactions = `-- name: ListLedgerTransactions :many
SELECT id, business_id, transaction_date, description, reference_number, created_by_user_id, created_at, updated_at, deleted_at FROM ledger_transaction
WHERE business_id = $1 AND deleted_at IS NULL AND id < $2
ORDER BY id DESC
LIMIT $3
`

type ListLedgerTransactionsParams struct {
	BusinessID int64 `json:"business_id"`
	BeforeID   int64 `json:"before_id"`
	PageLimit  int32 `json:"page_limit"`
}

func (q *Queries) ListLedgerTransactions(ctx context.Context, arg ListLedgerTransactionsParams) ([]LedgerTransaction, error) {
	rows, err := q.db.Query(ctx, listLedgerTransactions, arg.BusinessID, arg.BeforeID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerTransaction
	for rows.Next() {
		var i LedgerTransaction
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.TransactionDate,
			&i.Description,
			&i.ReferenceNumber,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteLedgerEntriesByTransaction = `-- name: SoftDeleteLedgerEntriesByTransaction :exec
UPDATE ledger_entry SET deleted_at = NOW()
WHERE ledger_transaction_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteLedgerEntriesByTransaction(ctx context.Context, ledgerTransactionID int64) error {
	_, err := q.db.Exec(ctx, softDeleteLedgerEntriesByTransaction, ledgerTransactionID)
	return err
}

const updateLedgerAccount = `-- name: UpdateLedgerAccount :one
UPDATE ledger_account SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    is_reconcilable = COALESCE($3, is_reconcilable),
    cash_flow_category_id = COALESCE($4, cash_flow_category_id),
    balance_sheet_category_id = COALESCE($5, balance_sheet_category_id),
    income_statement_category_id = COALESCE($6, income_statement_category_id),
    updated_at = NOW()
WHERE id = $7
RETURNING id, business_id, account_type_id, code, name, description, is_system, is_reconcilable, display_sequence, cash_flow_category_id, balance_sheet_category_id, income_statement_category_id, is_active, created_by_user_id, created_at, updated_at
`

type UpdateLedgerAccountParams struct {
	Name                      *string `json:"name"`
	Description               *string `json:"description"`
	IsReconcilable            *bool   `json:"is_reconcilable"`
	CashFlowCategoryID        *int32  `json:"cash_flow_category_id"`
	BalanceSheetCategoryID    *int32  `json:"balance_sheet_category_id"`
	IncomeStatementCategoryID *int32  `json:"income_statement_category_id"`
	ID                        int32   `json:"id"`
}

func (q *Queries) UpdateLedgerAccount(ctx context.Context, arg UpdateLedgerAccountParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, updateLedgerAccount,
		arg.Name,
		arg.Description,
		arg.IsReconcilable,
		arg.CashFlowCategoryID,
		arg.BalanceSheetCategoryID,
		arg.IncomeStatementCategoryID,
		arg.ID,
	)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.AccountTypeID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.IsReconcilable,
		&i.DisplaySequence,
		&i.CashFlowCategoryID,
		&i.BalanceSheetCategoryID,
		&i.IncomeStatementCategoryID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
