// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: party.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContact = `-- name: CreateContact :one

INSERT INTO contact (
    business_id, ledger_account_id, contact_number, is_customer, is_vendor, name,
    email, phone, payment_terms_days, credit_limit, created_by_user_id,
    billing_address_line1, billing_address_line2, billing_city, billing_state,
    billing_postal_code, billing_country
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING id, business_id, ledger_account_id, contact_number, is_customer, is_vendor, name, email, phone, billing_address_line1, billing_address_line2, billing_city, billing_state, billing_postal_code, billing_country, shipping_address_line1, shipping_address_line2, shipping_city, shipping_state, shipping_postal_code, shipping_country, payment_terms_days, credit_limit, is_active, created_by_user_id, created_at, updated_at, deleted_at
`

type CreateContactParams struct {
	BusinessID          int64          `json:"business_id"`
	LedgerAccountID     *int32         `json:"ledger_account_id"`
	ContactNumber       string         `json:"contact_number"`
	IsCustomer          bool           `json:"is_customer"`
	IsVendor            bool           `json:"is_vendor"`
	Name                string         `json:"name"`
	Email               *string        `json:"email"`
	Phone               *string        `json:"phone"`
	PaymentTermsDays    *int32         `json:"payment_terms_days"`
	CreditLimit         pgtype.Numeric `json:"credit_limit"`
	CreatedByUserID     *int64         `json:"created_by_user_id"`
	BillingAddressLine1 *string        `json:"billing_address_line1"`
	BillingAddressLine2 *string        `json:"billing_address_line2"`
	BillingCity         *string        `json:"billing_city"`
	BillingState        *string        `json:"billing_state"`
	BillingPostalCode   *string        `json:"billing_postal_code"`
	BillingCountry      *string        `json:"billing_country"`
}

// Copyright (c) 2025 Casey Entzi
// SPDX-License-Identifier: MIT
func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.BusinessID,
		arg.LedgerAccountID,
		arg.ContactNumber,
		arg.IsCustomer,
		arg.IsVendor,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.PaymentTermsDays,
		arg.CreditLimit,
		arg.CreatedByUserID,
		arg.BillingAddressLine1,
		arg.BillingAddressLine2,
		arg.BillingCity,
		arg.BillingState,
		arg.BillingPostalCode,
		arg.BillingCountry,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LedgerAccountID,
		&i.ContactNumber,
		&i.IsCustomer,
		&i.IsVendor,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.BillingAddressLine1,
		&i.BillingAddressLine2,
		&i.BillingCity,
		&i.BillingState,
		&i.BillingPostalCode,
		&i.BillingCountry,
		&i.ShippingAddressLine1,
		&i.ShippingAddressLine2,
		&i.ShippingCity,
		&i.ShippingState,
		&i.ShippingPostalCode,
		&i.ShippingCountry,
		&i.PaymentTermsDays,
		&i.CreditLimit,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createService = `-- name: CreateService :one
INSERT INTO service (
    business_id, service_code, name, description, unit_of_measure, cost_price,
    retail_price, is_taxable, default_tax_rate_id, created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, business_id, service_code, name, description, unit_of_measure, cost_price, retail_price, is_taxable, default_tax_rate_id, is_active, created_by_user_id, created_at, updated_at, deleted_at
`

type CreateServiceParams struct {
	BusinessID       int64          `json:"business_id"`
	ServiceCode      string         `json:"service_code"`
	Name             string         `json:"name"`
	Description      *string        `json:"description"`
	UnitOfMeasure    *string        `json:"unit_of_measure"`
	CostPrice        pgtype.Numeric `json:"cost_price"`
	RetailPrice      pgtype.Numeric `json:"retail_price"`
	IsTaxable        bool           `json:"is_taxable"`
	DefaultTaxRateID *int64         `json:"default_tax_rate_id"`
	CreatedByUserID  *int64         `json:"created_by_user_id"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.BusinessID,
		arg.ServiceCode,
		arg.Name,
		arg.Description,
		arg.UnitOfMeasure,
		arg.CostPrice,
		arg.RetailPrice,
		arg.IsTaxable,
		arg.DefaultTaxRateID,
		arg.CreatedByUserID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ServiceCode,
		&i.Name,
		&i.Description,
		&i.UnitOfMeasure,
		&i.CostPrice,
		&i.RetailPrice,
		&i.IsTaxable,
		&i.DefaultTaxRateID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTaxRate = `-- name: CreateTaxRate :one
INSERT INTO tax_rate (
    business_id, name, rate, tax_liability_account_id, created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, business_id, name, rate, tax_liability_account_id, is_active, created_by_user_id, created_at, updated_at
`

type CreateTaxRateParams struct {
	BusinessID            int64          `json:"business_id"`
	Name                  string         `json:"name"`
	Rate                  pgtype.Numeric `json:"rate"`
	TaxLiabilityAccountID int32          `json:"tax_liability_account_id"`
	CreatedByUserID       *int64         `json:"created_by_user_id"`
}

func (q *Queries) CreateTaxRate(ctx context.Context, arg CreateTaxRateParams) (TaxRate, error) {
	row := q.db.QueryRow(ctx, createTaxRate,
		arg.BusinessID,
		arg.Name,
		arg.Rate,
		arg.TaxLiabilityAccountID,
		arg.CreatedByUserID,
	)
	var i TaxRate
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Rate,
		&i.TaxLiabilityAccountID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateContact = `-- name: DeactivateContact :one
UPDATE contact SET is_active = FALSE, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, business_id, ledger_account_id, contact_number, is_customer, is_vendor, name, email, phone, billing_address_line1, billing_address_line2, billing_city, billing_state, billing_postal_code, billing_country, shipping_address_line1, shipping_address_line2, shipping_city, shipping_state, shipping_postal_code, shipping_country, payment_terms_days, credit_limit, is_active, created_by_user_id, created_at, updated_at, deleted_at
`

func (q *Queries) DeactivateContact(ctx context.Context, id int64) (Contact, error) {
	row := q.db.QueryRow(ctx, deactivateContact, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LedgerAccountID,
		&i.ContactNumber,
		&i.IsCustomer,
		&i.IsVendor,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.BillingAddressLine1,
		&i.BillingAddressLine2,
		&i.BillingCity,
		&i.BillingState,
		&i.BillingPostalCode,
		&i.BillingCountry,
		&i.ShippingAddressLine1,
		&i.ShippingAddressLine2,
		&i.ShippingCity,
		&i.ShippingState,
		&i.ShippingPostalCode,
		&i.ShippingCountry,
		&i.PaymentTermsDays,
		&i.CreditLimit,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deactivateService = `-- name: DeactivateService :one
UPDATE service SET is_active = FALSE, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, business_id, service_code, name, description, unit_of_measure, cost_price, retail_price, is_taxable, default_tax_rate_id, is_active, created_by_user_id, created_at, updated_at, deleted_at
`

func (q *Queries) DeactivateService(ctx context.Context, id int64) (Service, error) {
	row := q.db.QueryRow(ctx, deactivateService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ServiceCode,
		&i.Name,
		&i.Description,
		&i.UnitOfMeasure,
		&i.CostPrice,
		&i.RetailPrice,
		&i.IsTaxable,
		&i.DefaultTaxRateID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deactivateTaxRate = `-- name: DeactivateTaxRate :one
UPDATE tax_rate SET is_active = FALSE, updated_at = NOW()
WHERE id = $1
RETURNING id, business_id, name, rate, tax_liability_account_id, is_active, created_by_user_id, created_at, updated_at
`

func (q *Queries) DeactivateTaxRate(ctx context.Context, id int64) (TaxRate, error) {
	row := q.db.QueryRow(ctx, deactivateTaxRate, id)
	var i TaxRate
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Rate,
		&i.TaxLiabilityAccountID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContact = `-- name: GetContact :one
SELECT id, business_id, ledger_account_id, contact_number, is_customer, is_vendor, name, email, phone, billing_address_line1, billing_address_line2, billing_city, billing_state, billing_postal_code, billing_country, shipping_address_line1, shipping_address_line2, shipping_city, shipping_state, shipping_postal_code, shipping_country, payment_terms_days, credit_limit, is_active, created_by_user_id, created_at, updated_at, deleted_at FROM contact WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetContact(ctx context.Context, id int64) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LedgerAccountID,
		&i.ContactNumber,
		&i.IsCustomer,
		&i.IsVendor,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.BillingAddressLine1,
		&i.BillingAddressLine2,
		&i.BillingCity,
		&i.BillingState,
		&i.BillingPostalCode,
		&i.BillingCountry,
		&i.ShippingAddressLine1,
		&i.ShippingAddressLine2,
		&i.ShippingCity,
		&i.ShippingState,
		&i.ShippingPostalCode,
		&i.ShippingCountry,
		&i.PaymentTermsDays,
		&i.CreditLimit,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getService = `-- name: GetService :one
SELECT id, business_id, service_code, name, description, unit_of_measure, cost_price, retail_price, is_taxable, default_tax_rate_id, is_active, created_by_user_id, created_at, updated_at, deleted_at FROM service WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetService(ctx context.Context, id int64) (Service, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ServiceCode,
		&i.Name,
		&i.Description,
		&i.UnitOfMeasure,
		&i.CostPrice,
		&i.RetailPrice,
		&i.IsTaxable,
		&i.DefaultTaxRateID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTaxRate = `-- name: GetTaxRate :one
SELECT id, business_id, name, rate, tax_liability_account_id, is_active, created_by_user_id, created_at, updated_at FROM tax_rate WHERE id = $1
`

func (q *Queries) GetTaxRate(ctx context.Context, id int64) (TaxRate, error) {
	row := q.db.QueryRow(ctx, getTaxRate, id)
	var i TaxRate
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Rate,
		&i.TaxLiabilityAccountID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContacts = `-- name: ListContacts :many
SELECT id, business_id, ledger_account_id, contact_number, is_customer, is_vendor, name, email, phone, billing_address_line1, billing_address_line2, billing_city, billing_state, billing_postal_code, billing_country, shipping_address_line1, shipping_address_line2, shipping_city, shipping_state, shipping_postal_code, shipping_country, payment_terms_days, credit_limit, is_active, created_by_user_id, created_at, updated_at, deleted_at FROM contact
WHERE business_id = $1 AND deleted_at IS NULL
    AND (is_active OR $2::bool)
ORDER BY name
`

type ListContactsParams struct {
	BusinessID      int64 `json:"business_id"`
	IncludeInactive bool  `json:"include_inactive"`
}

func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContacts, arg.BusinessID, arg.IncludeInactive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.LedgerAccountID,
			&i.ContactNumber,
			&i.IsCustomer,
			&i.IsVendor,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.BillingAddressLine1,
			&i.BillingAddressLine2,
			&i.BillingCity,
			&i.BillingState,
			&i.BillingPostalCode,
			&i.BillingCountry,
			&i.ShippingAddressLine1,
			&i.ShippingAddressLine2,
			&i.ShippingCity,
			&i.ShippingState,
			&i.ShippingPostalCode,
			&i.ShippingCountry,
			&i.PaymentTermsDays,
			&i.CreditLimit,
			&i.IsActive,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT id, business_id, service_code, name, description, unit_of_measure, cost_price, retail_price, is_taxable, default_tax_rate_id, is_active, created_by_user_id, created_at, updated_at, deleted_at FROM service
WHERE business_id = $1 AND deleted_at IS NULL
    AND (is_active OR $2::bool)
ORDER BY service_code
`

type ListServicesParams struct {
	BusinessID      int64 `json:"business_id"`
	IncludeInactive bool  `json:"include_inactive"`
}

func (q *Queries) ListServices(ctx context.Context, arg ListServicesParams) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices, arg.BusinessID, arg.IncludeInactive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.ServiceCode,
			&i.Name,
			&i.Description,
			&i.UnitOfMeasure,
			&i.CostPrice,
			&i.RetailPrice,
			&i.IsTaxable,
			&i.DefaultTaxRateID,
			&i.IsActive,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxRates = `-- name: ListTaxRates :many
SELECT id, business_id, name, rate, tax_liability_account_id, is_active, created_by_user_id, created_at, updated_at FROM tax_rate WHERE business_id = $1 ORDER BY name
`

func (q *Queries) ListTaxRates(ctx context.Context, businessID int64) ([]TaxRate, error) {
	rows, err := q.db.Query(ctx, listTaxRates, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaxRate
	for rows.Next() {
		var i TaxRate
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.Rate,
			&i.TaxLiabilityAccountID,
			&i.IsActive,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
UPDATE contact SET
    name = COALESCE($1, name),
    email = COALESCE($2, email),
    phone = COALESCE($3, phone),
    ledger_account_id = COALESCE($4, ledger_account_id),
    payment_terms_days = COALESCE($5, payment_terms_days),
    credit_limit = COALESCE($6, credit_limit),
    billing_address_line1 = COALESCE($7, billing_address_line1),
    billing_address_line2 = COALESCE($8, billing_address_line2),
    billing_city = COALESCE($9, billing_city),
    billing_state = COALESCE($10, billing_state),
    billing_postal_code = COALESCE($11, billing_postal_code),
    billing_country = COALESCE($12, billing_country),
    updated_at = NOW()
WHERE id = $13 AND deleted_at IS NULL
RETURNING id, business_id, ledger_account_id, contact_number, is_customer, is_vendor, name, email, phone, billing_address_line1, billing_address_line2, billing_city, billing_state, billing_postal_code, billing_country, shipping_address_line1, shipping_address_line2, shipping_city, shipping_state, shipping_postal_code, shipping_country, payment_terms_days, credit_limit, is_active, created_by_user_id, created_at, updated_at, deleted_at
`

type UpdateContactParams struct {
	Name                *string        `json:"name"`
	Email               *string        `json:"email"`
	Phone               *string        `json:"phone"`
	LedgerAccountID     *int32         `json:"ledger_account_id"`
	PaymentTermsDays    *int32         `json:"payment_terms_days"`
	CreditLimit         pgtype.Numeric `json:"credit_limit"`
	BillingAddressLine1 *string        `json:"billing_address_line1"`
	BillingAddressLine2 *string        `json:"billing_address_line2"`
	BillingCity         *string        `json:"billing_city"`
	BillingState        *string        `json:"billing_state"`
	BillingPostalCode   *string        `json:"billing_postal_code"`
	BillingCountry      *string        `json:"billing_country"`
	ID                  int64          `json:"id"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.LedgerAccountID,
		arg.PaymentTermsDays,
		arg.CreditLimit,
		arg.BillingAddressLine1,
		arg.BillingAddressLine2,
		arg.BillingCity,
		arg.BillingState,
		arg.BillingPostalCode,
		arg.BillingCountry,
		arg.ID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LedgerAccountID,
		&i.ContactNumber,
		&i.IsCustomer,
		&i.IsVendor,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.BillingAddressLine1,
		&i.BillingAddressLine2,
		&i.BillingCity,
		&i.BillingState,
		&i.BillingPostalCode,
		&i.BillingCountry,
		&i.ShippingAddressLine1,
		&i.ShippingAddressLine2,
		&i.ShippingCity,
		&i.ShippingState,
		&i.ShippingPostalCode,
		&i.ShippingCountry,
		&i.PaymentTermsDays,
		&i.CreditLimit,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateService = `-- name: UpdateService :one
UPDATE service SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    retail_price = COALESCE($3, retail_price),
    cost_price = COALESCE($4, cost_price),
    is_taxable = COALESCE($5, is_taxable),
    default_tax_rate_id = COALESCE($6, default_tax_rate_id),
    updated_at = NOW()
WHERE id = $7 AND deleted_at IS NULL
RETURNING id, business_id, service_code, name, description, unit_of_measure, cost_price, retail_price, is_taxable, default_tax_rate_id, is_active, created_by_user_id, created_at, updated_at, deleted_at
`

type UpdateServiceParams struct {
	Name             *string        `json:"name"`
	Description      *string        `json:"description"`
	RetailPrice      pgtype.Numeric `json:"retail_price"`
	CostPrice        pgtype.Numeric `json:"cost_price"`
	IsTaxable        *bool          `json:"is_taxable"`
	DefaultTaxRateID *int64         `json:"default_tax_rate_id"`
	ID               int64          `json:"id"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.Name,
		arg.Description,
		arg.RetailPrice,
		arg.CostPrice,
		arg.IsTaxable,
		arg.DefaultTaxRateID,
		arg.ID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ServiceCode,
		&i.Name,
		&i.Description,
		&i.UnitOfMeasure,
		&i.CostPrice,
		&i.RetailPrice,
		&i.IsTaxable,
		&i.DefaultTaxRateID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTaxRate = `-- name: UpdateTaxRate :one
UPDATE tax_rate SET
    name = COALESCE($1, name),
    rate = COALESCE($2, rate),
    updated_at = NOW()
WHERE id = $3
RETURNING id, business_id, name, rate, tax_liability_account_id, is_active, created_by_user_id, created_at, updated_at
`

type UpdateTaxRateParams struct {
	Name *string        `json:"name"`
	Rate pgtype.Numeric `json:"rate"`
	ID   int64          `json:"id"`
}

func (q *Queries) UpdateTaxRate(ctx context.Context, arg UpdateTaxRateParams) (TaxRate, error) {
	row := q.db.QueryRow(ctx, updateTaxRate, arg.Name, arg.Rate, arg.ID)
	var i TaxRate
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Rate,
		&i.TaxLiabilityAccountID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
