// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trading.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyPaymentToInvoice = `-- name: ApplyPaymentToInvoice :one
UPDATE invoice SET
    paid_amount = paid_amount + $1,
    balance_due = balance_due - $1,
    status = CASE WHEN balance_due - $1 <= 0 THEN 'PAID' ELSE status END,
    updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, business_id, contact_id, invoice_type, estimate_id, invoice_number, invoice_date, due_date, subtotal, total_tax_amount, discount_amount, total_amount, paid_amount, balance_due, status, notes, terms, ledger_transaction_id, created_by_user_id, created_at, updated_at, resource_version, deleted_at
`

type ApplyPaymentToInvoiceParams struct {
	Amount pgtype.Numeric `json:"amount"`
	ID     int64          `json:"id"`
}

func (q *Queries) ApplyPaymentToInvoice(ctx context.Context, arg ApplyPaymentToInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, applyPaymentToInvoice, arg.Amount, arg.ID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ContactID,
		&i.InvoiceType,
		&i.EstimateID,
		&i.InvoiceNumber,
		&i.InvoiceDate,
		&i.DueDate,
		&i.Subtotal,
		&i.TotalTaxAmount,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.BalanceDue,
		&i.Status,
		&i.Notes,
		&i.Terms,
		&i.LedgerTransactionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
		&i.DeletedAt,
	)
	return i, err
}

const createEstimate = `-- name: CreateEstimate :one

INSERT INTO estimate (
    business_id, customer_id, estimate_number, estimate_date, expiration_date,
    subtotal, total_tax_amount, total_amount, notes, terms, created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, business_id, customer_id, estimate_number, estimate_date, expiration_date, subtotal, total_tax_amount, discount_amount, total_amount, status, notes, terms, created_by_user_id, created_at, updated_at, resource_version, deleted_at
`

type CreateEstimateParams struct {
	BusinessID      int64          `json:"business_id"`
	CustomerID      int64          `json:"customer_id"`
	EstimateNumber  string         `json:"estimate_number"`
	EstimateDate    pgtype.Date    `json:"estimate_date"`
	ExpirationDate  pgtype.Date    `json:"expiration_date"`
	Subtotal        pgtype.Numeric `json:"subtotal"`
	TotalTaxAmount  pgtype.Numeric `json:"total_tax_amount"`
	TotalAmount     pgtype.Numeric `json:"total_amount"`
	Notes           *string        `json:"notes"`
	Terms           *string        `json:"terms"`
	CreatedByUserID *int64         `json:"created_by_user_id"`
}

// Copyright (c) 2025 Casey Entzi
// SPDX-License-Identifier: MIT
func (q *Queries) CreateEstimate(ctx context.Context, arg CreateEstimateParams) (Estimate, error) {
	row := q.db.QueryRow(ctx, createEstimate,
		arg.BusinessID,
		arg.CustomerID,
		arg.EstimateNumber,
		arg.EstimateDate,
		arg.ExpirationDate,
		arg.Subtotal,
		arg.TotalTaxAmount,
		arg.TotalAmount,
		arg.Notes,
		arg.Terms,
		arg.CreatedByUserID,
	)
	var i Estimate
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CustomerID,
		&i.EstimateNumber,
		&i.EstimateDate,
		&i.ExpirationDate,
		&i.Subtotal,
		&i.TotalTaxAmount,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.Status,
		&i.Notes,
		&i.Terms,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
		&i.DeletedAt,
	)
	return i, err
}

const createEstimateLineItem = `-- name: CreateEstimateLineItem :one
INSERT INTO estimate_line_item (
    estimate_id, service_id, line_number, description, quantity, unit_price,
    line_subtotal, is_taxable, tax_rate_id, tax_rate, tax_amount, line_total
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, estimate_id, service_id, line_number, description, quantity, unit_price, line_subtotal, is_taxable, tax_rate_id, tax_rate, tax_amount, line_total, created_at, updated_at, deleted_at
`

type CreateEstimateLineItemParams struct {
	EstimateID   int64          `json:"estimate_id"`
	ServiceID    *int64         `json:"service_id"`
	LineNumber   int32          `json:"line_number"`
	Description  string         `json:"description"`
	Quantity     pgtype.Numeric `json:"quantity"`
	UnitPrice    pgtype.Numeric `json:"unit_price"`
	LineSubtotal pgtype.Numeric `json:"line_subtotal"`
	IsTaxable    bool           `json:"is_taxable"`
	TaxRateID    *int64         `json:"tax_rate_id"`
	TaxRate      pgtype.Numeric `json:"tax_rate"`
	TaxAmount    pgtype.Numeric `json:"tax_amount"`
	LineTotal    pgtype.Numeric `json:"line_total"`
}

func (q *Queries) CreateEstimateLineItem(ctx context.Context, arg CreateEstimateLineItemParams) (EstimateLineItem, error) {
	row := q.db.QueryRow(ctx, createEstimateLineItem,
		arg.EstimateID,
		arg.ServiceID,
		arg.LineNumber,
		arg.Description,
		arg.Quantity,
		arg.UnitPrice,
		arg.LineSubtotal,
		arg.IsTaxable,
		arg.TaxRateID,
		arg.TaxRate,
		arg.TaxAmount,
		arg.LineTotal,
	)
	var i EstimateLineItem
	err := row.Scan(
		&i.ID,
		&i.EstimateID,
		&i.ServiceID,
		&i.LineNumber,
		&i.Description,
		&i.Quantity,
		&i.UnitPrice,
		&i.LineSubtotal,
		&i.IsTaxable,
		&i.TaxRateID,
		&i.TaxRate,
		&i.TaxAmount,
		&i.LineTotal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoice (
    business_id, contact_id, invoice_type, estimate_id, invoice_number, invoice_date,
    due_date, subtotal, total_tax_amount, total_amount, balance_due, notes, terms,
    created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, business_id, contact_id, invoice_type, estimate_id, invoice_number, invoice_date, due_date, subtotal, total_tax_amount, discount_amount, total_amount, paid_amount, balance_due, status, notes, terms, ledger_transaction_id, created_by_user_id, created_at, updated_at, resource_version, deleted_at
`

type CreateInvoiceParams struct {
	BusinessID      int64          `json:"business_id"`
	ContactID       int64          `json:"contact_id"`
	InvoiceType     string         `json:"invoice_type"`
	EstimateID      *int64         `json:"estimate_id"`
	InvoiceNumber   string         `json:"invoice_number"`
	InvoiceDate     pgtype.Date    `json:"invoice_date"`
	DueDate         pgtype.Date    `json:"due_date"`
	Subtotal        pgtype.Numeric `json:"subtotal"`
	TotalTaxAmount  pgtype.Numeric `json:"total_tax_amount"`
	TotalAmount     pgtype.Numeric `json:"total_amount"`
	BalanceDue      pgtype.Numeric `json:"balance_due"`
	Notes           *string        `json:"notes"`
	Terms           *string        `json:"terms"`
	CreatedByUserID *int64         `json:"created_by_user_id"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.BusinessID,
		arg.ContactID,
		arg.InvoiceType,
		arg.EstimateID,
		arg.InvoiceNumber,
		arg.InvoiceDate,
		arg.DueDate,
		arg.Subtotal,
		arg.TotalTaxAmount,
		arg.TotalAmount,
		arg.BalanceDue,
		arg.Notes,
		arg.Terms,
		arg.CreatedByUserID,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ContactID,
		&i.InvoiceType,
		&i.EstimateID,
		&i.InvoiceNumber,
		&i.InvoiceDate,
		&i.DueDate,
		&i.Subtotal,
		&i.TotalTaxAmount,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.BalanceDue,
		&i.Status,
		&i.Notes,
		&i.Terms,
		&i.LedgerTransactionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
		&i.DeletedAt,
	)
	return i, err
}

const createInvoiceLineItem = `-- name: CreateInvoiceLineItem :one
INSERT INTO invoice_line_item (
    invoice_id, service_id, ledger_account_id, line_number, description, quantity,
    unit_price, line_subtotal, is_taxable, tax_rate_id, tax_rate, tax_amount, line_total
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, invoice_id, service_id, ledger_account_id, line_number, description, quantity, unit_price, line_subtotal, is_taxable, tax_rate_id, tax_rate, tax_amount, line_total, created_at, updated_at, deleted_at
`

type CreateInvoiceLineItemParams struct {
	InvoiceID       int64          `json:"invoice_id"`
	ServiceID       *int64         `json:"service_id"`
	LedgerAccountID *int32         `json:"ledger_account_id"`
	LineNumber      int32          `json:"line_number"`
	Description     string         `json:"description"`
	Quantity        pgtype.Numeric `json:"quantity"`
	UnitPrice       pgtype.Numeric `json:"unit_price"`
	LineSubtotal    pgtype.Numeric `json:"line_subtotal"`
	IsTaxable       bool           `json:"is_taxable"`
	TaxRateID       *int64         `json:"tax_rate_id"`
	TaxRate         pgtype.Numeric `json:"tax_rate"`
	TaxAmount       pgtype.Numeric `json:"tax_amount"`
	LineTotal       pgtype.Numeric `json:"line_total"`
}

func (q *Queries) CreateInvoiceLineItem(ctx context.Context, arg CreateInvoiceLineItemParams) (InvoiceLineItem, error) {
	row := q.db.QueryRow(ctx, createInvoiceLineItem,
		arg.InvoiceID,
		arg.ServiceID,
		arg.LedgerAccountID,
		arg.LineNumber,
		arg.Description,
		arg.Quantity,
		arg.UnitPrice,
		arg.LineSubtotal,
		arg.IsTaxable,
		arg.TaxRateID,
		arg.TaxRate,
		arg.TaxAmount,
		arg.LineTotal,
	)
	var i InvoiceLineItem
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ServiceID,
		&i.LedgerAccountID,
		&i.LineNumber,
		&i.Description,
		&i.Quantity,
		&i.UnitPrice,
		&i.LineSubtotal,
		&i.IsTaxable,
		&i.TaxRateID,
		&i.TaxRate,
		&i.TaxAmount,
		&i.LineTotal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payment (
    business_id, contact_id, payment_type, payment_number, payment_date,
    amount, payment_method, ledger_account_id, reference_number, notes, created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, business_id, contact_id, payment_type, payment_number, payment_date, amount, payment_method, reference_number, notes, ledger_account_id, ledger_transaction_id, created_by_user_id, created_at, updated_at, deleted_at
`

type CreatePaymentParams struct {
	BusinessID      int64          `json:"business_id"`
	ContactID       int64          `json:"contact_id"`
	PaymentType     string         `json:"payment_type"`
	PaymentNumber   string         `json:"payment_number"`
	PaymentDate     pgtype.Date    `json:"payment_date"`
	Amount          pgtype.Numeric `json:"amount"`
	PaymentMethod   string         `json:"payment_method"`
	LedgerAccountID *int32         `json:"ledger_account_id"`
	ReferenceNumber *string        `json:"reference_number"`
	Notes           *string        `json:"notes"`
	CreatedByUserID *int64         `json:"created_by_user_id"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.BusinessID,
		arg.ContactID,
		arg.PaymentType,
		arg.PaymentNumber,
		arg.PaymentDate,
		arg.Amount,
		arg.PaymentMethod,
		arg.LedgerAccountID,
		arg.ReferenceNumber,
		arg.Notes,
		arg.CreatedByUserID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ContactID,
		&i.PaymentType,
		&i.PaymentNumber,
		&i.PaymentDate,
		&i.Amount,
		&i.PaymentMethod,
		&i.ReferenceNumber,
		&i.Notes,
		&i.LedgerAccountID,
		&i.LedgerTransactionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPaymentApplication = `-- name: CreatePaymentApplication :one
INSERT INTO payment_application (payment_id, invoice_id, applied_amount)
VALUES ($1, $2, $3)
RETURNING id, payment_id, invoice_id, applied_amount, created_at
`

type CreatePaymentApplicationParams struct {
	PaymentID     int64          `json:"payment_id"`
	InvoiceID     int64          `json:"invoice_id"`
	AppliedAmount pgtype.Numeric `json:"applied_amount"`
}

func (q *Queries) CreatePaymentApplication(ctx context.Context, arg CreatePaymentApplicationParams) (PaymentApplication, error) {
	row := q.db.QueryRow(ctx, createPaymentApplication, arg.PaymentID, arg.InvoiceID, arg.AppliedAmount)
	var i PaymentApplication
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.InvoiceID,
		&i.AppliedAmount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEstimateLineItems = `-- name: DeleteEstimateLineItems :exec
UPDATE estimate_line_item SET deleted_at = NOW()
WHERE estimate_id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteEstimateLineItems(ctx context.Context, estimateID int64) error {
	_, err := q.db.Exec(ctx, deleteEstimateLineItems, estimateID)
	return err
}

const deleteInvoiceLineItems = `-- name: DeleteInvoiceLineItems :exec
UPDATE invoice_line_item SET deleted_at = NOW()
WHERE invoice_id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteInvoiceLineItems(ctx context.Context, invoiceID int64) error {
	_, err := q.db.Exec(ctx, deleteInvoiceLineItems, invoiceID)
	return err
}

const getEstimate = `-- name: GetEstimate :one
SELECT id, business_id, customer_id, estimate_number, estimate_date, expiration_date, subtotal, total_tax_amount, discount_amount, total_amount, status, notes, terms, created_by_user_id, created_at, updated_at, resource_version, deleted_at FROM estimate WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEstimate(ctx context.Context, id int64) (Estimate, error) {
	row := q.db.QueryRow(ctx, getEstimate, id)
	var i Estimate
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CustomerID,
		&i.EstimateNumber,
		&i.EstimateDate,
		&i.ExpirationDate,
		&i.Subtotal,
		&i.TotalTaxAmount,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.Status,
		&i.Notes,
		&i.Terms,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
		&i.DeletedAt,
	)
	return i, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, business_id, contact_id, invoice_type, estimate_id, invoice_number, invoice_date, due_date, subtotal, total_tax_amount, discount_amount, total_amount, paid_amount, balance_due, status, notes, terms, ledger_transaction_id, created_by_user_id, created_at, updated_at, resource_version, deleted_at FROM invoice WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetInvoice(ctx context.Context, id int64) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ContactID,
		&i.InvoiceType,
		&i.EstimateID,
		&i.InvoiceNumber,
		&i.InvoiceDate,
		&i.DueDate,
		&i.Subtotal,
		&i.TotalTaxAmount,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.BalanceDue,
		&i.Status,
		&i.Notes,
		&i.Terms,
		&i.LedgerTransactionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
		&i.DeletedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, business_id, contact_id, payment_type, payment_number, payment_date, amount, payment_method, reference_number, notes, ledger_account_id, ledger_transaction_id, created_by_user_id, created_at, updated_at, deleted_at FROM payment WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPayment(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ContactID,
		&i.PaymentType,
		&i.PaymentNumber,
		&i.PaymentDate,
		&i.Amount,
		&i.PaymentMethod,
		&i.ReferenceNumber,
		&i.Notes,
		&i.LedgerAccountID,
		&i.LedgerTransactionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listEstimateLineItems = `-- name: ListEstimateLineItems :many
SELECT id, estimate_id, service_id, line_number, description, quantity, unit_price, line_subtotal, is_taxable, tax_rate_id, tax_rate, tax_amount, line_total, created_at, updated_at, deleted_at FROM estimate_line_item WHERE estimate_id = $1 AND deleted_at IS NULL ORDER BY line_number
`

func (q *Queries) ListEstimateLineItems(ctx context.Context, estimateID int64) ([]EstimateLineItem, error) {
	rows, err := q.db.Query(ctx, listEstimateLineItems, estimateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EstimateLineItem
	for rows.Next() {
		var i EstimateLineItem
		if err := rows.Scan(
			&i.ID,
			&i.EstimateID,
			&i.ServiceID,
			&i.LineNumber,
			&i.Description,
			&i.Quantity,
			&i.UnitPrice,
			&i.LineSubtotal,
			&i.IsTaxable,
			&i.TaxRateID,
			&i.TaxRate,
			&i.TaxAmount,
			&i.LineTotal,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEstimates = `-- name: ListEstimates :many
SELECT id, business_id, customer_id, estimate_number, estimate_date, expiration_date, subtotal, total_tax_amount, discount_amount, total_amount, status, notes, terms, created_by_user_id, created_at, updated_at, resource_version, deleted_at FROM estimate
WHERE business_id = $1 AND deleted_at IS NULL
    AND ($2::bool OR status IN ('DRAFT', 'SENT'))
ORDER BY estimate_date DESC
`

type ListEstimatesParams struct {
	BusinessID int64 `json:"business_id"`
	IncludeAll bool  `json:"include_all"`
}

func (q *Queries) ListEstimates(ctx context.Context, arg ListEstimatesParams) ([]Estimate, error) {
	rows, err := q.db.Query(ctx, listEstimates, arg.BusinessID, arg.IncludeAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Estimate
	for rows.Next() {
		var i Estimate
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.CustomerID,
			&i.EstimateNumber,
			&i.EstimateDate,
			&i.ExpirationDate,
			&i.Subtotal,
			&i.TotalTaxAmount,
			&i.DiscountAmount,
			&i.TotalAmount,
			&i.Status,
			&i.Notes,
			&i.Terms,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResourceVersion,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceLineItems = `-- name: ListInvoiceLineItems :many
SELECT id, invoice_id, service_id, ledger_account_id, line_number, description, quantity, unit_price, line_subtotal, is_taxable, tax_rate_id, tax_rate, tax_amount, line_total, created_at, updated_at, deleted_at FROM invoice_line_item WHERE invoice_id = $1 AND deleted_at IS NULL ORDER BY line_number
`

func (q *Queries) ListInvoiceLineItems(ctx context.Context, invoiceID int64) ([]InvoiceLineItem, error) {
	rows, err := q.db.Query(ctx, listInvoiceLineItems, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoiceLineItem
	for rows.Next() {
		var i InvoiceLineItem
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.ServiceID,
			&i.LedgerAccountID,
			&i.LineNumber,
			&i.Description,
			&i.Quantity,
			&i.UnitPrice,
			&i.LineSubtotal,
			&i.IsTaxable,
			&i.TaxRateID,
			&i.TaxRate,
			&i.TaxAmount,
			&i.LineTotal,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, business_id, contact_id, invoice_type, estimate_id, invoice_number, invoice_date, due_date, subtotal, total_tax_amount, discount_amount, total_amount, paid_amount, balance_due, status, notes, terms, ledger_transaction_id, created_by_user_id, created_at, updated_at, resource_version, deleted_at FROM invoice
WHERE business_id = $1 AND deleted_at IS NULL
    AND ($2::bool OR status NOT IN ('PAID', 'CANCELLED'))
ORDER BY invoice_date DESC
`

type ListInvoicesParams struct {
	BusinessID int64 `json:"business_id"`
	IncludeAll bool  `json:"include_all"`
}

func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoices, arg.BusinessID, arg.IncludeAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.ContactID,
			&i.InvoiceType,
			&i.EstimateID,
			&i.InvoiceNumber,
			&i.InvoiceDate,
			&i.DueDate,
			&i.Subtotal,
			&i.TotalTaxAmount,
			&i.DiscountAmount,
			&i.TotalAmount,
			&i.PaidAmount,
			&i.BalanceDue,
			&i.Status,
			&i.Notes,
			&i.Terms,
			&i.LedgerTransactionID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResourceVersion,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesForContact = `-- name: ListInvoicesForContact :many
SELECT id, business_id, contact_id, invoice_type, estimate_id, invoice_number, invoice_date, due_date, subtotal, total_tax_amount, discount_amount, total_amount, paid_amount, balance_due, status, notes, terms, ledger_transaction_id, created_by_user_id, created_at, updated_at, resource_version, deleted_at FROM invoice
WHERE contact_id = $1 AND deleted_at IS NULL
    AND invoice_date BETWEEN $2 AND $3
ORDER BY invoice_date
`

type ListInvoicesForContactParams struct {
	ContactID   int64       `json:"contact_id"`
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
}

func (q *Queries) ListInvoicesForContact(ctx context.Context, arg ListInvoicesForContactParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesForContact, arg.ContactID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.ContactID,
			&i.InvoiceType,
			&i.EstimateID,
			&i.InvoiceNumber,
			&i.InvoiceDate,
			&i.DueDate,
			&i.Subtotal,
			&i.TotalTaxAmount,
			&i.DiscountAmount,
			&i.TotalAmount,
			&i.PaidAmount,
			&i.BalanceDue,
			&i.Status,
			&i.Notes,
			&i.Terms,
			&i.LedgerTransactionID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResourceVersion,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentApplicationsForPayment = `-- name: ListPaymentApplicationsForPayment :many
SELECT id, payment_id, invoice_id, applied_amount, created_at FROM payment_application WHERE payment_id = $1 ORDER BY id
`

func (q *Queries) ListPaymentApplicationsForPayment(ctx context.Context, paymentID int64) ([]PaymentApplication, error) {
	rows, err := q.db.Query(ctx, listPaymentApplicationsForPayment, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentApplication
	for rows.Next() {
		var i PaymentApplication
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.InvoiceID,
			&i.AppliedAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayments = `-- name: ListPayments :many
SELECT id, business_id, contact_id, payment_type, payment_number, payment_date, amount, payment_method, reference_number, notes, ledger_account_id, ledger_transaction_id, created_by_user_id, created_at, updated_at, deleted_at FROM payment WHERE business_id = $1 AND deleted_at IS NULL ORDER BY payment_date DESC
`

func (q *Queries) ListPayments(ctx context.Context, businessID int64) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPayments, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.ContactID,
			&i.PaymentType,
			&i.PaymentNumber,
			&i.PaymentDate,
			&i.Amount,
			&i.PaymentMethod,
			&i.ReferenceNumber,
			&i.Notes,
			&i.LedgerAccountID,
			&i.LedgerTransactionID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsForContact = `-- name: ListPaymentsForContact :many
SELECT id, business_id, contact_id, payment_type, payment_number, payment_date, amount, payment_method, reference_number, notes, ledger_account_id, ledger_transaction_id, created_by_user_id, created_at, updated_at, deleted_at FROM payment
WHERE contact_id = $1 AND deleted_at IS NULL
    AND payment_date BETWEEN $2 AND $3
ORDER BY payment_date
`

type ListPaymentsForContactParams struct {
	ContactID   int64       `json:"contact_id"`
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
}

func (q *Queries) ListPaymentsForContact(ctx context.Context, arg ListPaymentsForContactParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsForContact, arg.ContactID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.ContactID,
			&i.PaymentType,
			&i.PaymentNumber,
			&i.PaymentDate,
			&i.Amount,
			&i.PaymentMethod,
			&i.ReferenceNumber,
			&i.Notes,
			&i.LedgerAccountID,
			&i.LedgerTransactionID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInvoiceLedgerTransaction = `-- name: SetInvoiceLedgerTransaction :one
UPDATE invoice SET ledger_transaction_id = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, business_id, contact_id, invoice_type, estimate_id, invoice_number, invoice_date, due_date, subtotal, total_tax_amount, discount_amount, total_amount, paid_amount, balance_due, status, notes, terms, ledger_transaction_id, created_by_user_id, created_at, updated_at, resource_version, deleted_at
`

type SetInvoiceLedgerTransactionParams struct {
	ID                  int64  `json:"id"`
	LedgerTransactionID *int64 `json:"ledger_transaction_id"`
}

func (q *Queries) SetInvoiceLedgerTransaction(ctx context.Context, arg SetInvoiceLedgerTransactionParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, setInvoiceLedgerTransaction, arg.ID, arg.LedgerTransactionID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ContactID,
		&i.InvoiceType,
		&i.EstimateID,
		&i.InvoiceNumber,
		&i.InvoiceDate,
		&i.DueDate,
		&i.Subtotal,
		&i.TotalTaxAmount,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.BalanceDue,
		&i.Status,
		&i.Notes,
		&i.Terms,
		&i.LedgerTransactionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
		&i.DeletedAt,
	)
	return i, err
}

const setPaymentLedgerTransaction = `-- name: SetPaymentLedgerTransaction :one
UPDATE payment SET ledger_transaction_id = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, business_id, contact_id, payment_type, payment_number, payment_date, amount, payment_method, reference_number, notes, ledger_account_id, ledger_transaction_id, created_by_user_id, created_at, updated_at, deleted_at
`

type SetPaymentLedgerTransactionParams struct {
	ID                  int64  `json:"id"`
	LedgerTransactionID *int64 `json:"ledger_transaction_id"`
}

func (q *Queries) SetPaymentLedgerTransaction(ctx context.Context, arg SetPaymentLedgerTransactionParams) (Payment, error) {
	row := q.db.QueryRow(ctx, setPaymentLedgerTransaction, arg.ID, arg.LedgerTransactionID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ContactID,
		&i.PaymentType,
		&i.PaymentNumber,
		&i.PaymentDate,
		&i.Amount,
		&i.PaymentMethod,
		&i.ReferenceNumber,
		&i.Notes,
		&i.LedgerAccountID,
		&i.LedgerTransactionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateEstimateStatus = `-- name: UpdateEstimateStatus :one
UPDATE estimate SET status = $1, updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL
    AND ($3::bigint IS NULL OR resource_version = $3)
RETURNING id, business_id, customer_id, estimate_number, estimate_date, expiration_date, subtotal, total_tax_amount, discount_amount, total_amount, status, notes, terms, created_by_user_id, created_at, updated_at, resource_version, deleted_at
`

type UpdateEstimateStatusParams struct {
	Status          string `json:"status"`
	ID              int64  `json:"id"`
	ResourceVersion *int64 `json:"resource_version"`
}

func (q *Queries) UpdateEstimateStatus(ctx context.Context, arg UpdateEstimateStatusParams) (Estimate, error) {
	row := q.db.QueryRow(ctx, updateEstimateStatus, arg.Status, arg.ID, arg.ResourceVersion)
	var i Estimate
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CustomerID,
		&i.EstimateNumber,
		&i.EstimateDate,
		&i.ExpirationDate,
		&i.Subtotal,
		&i.TotalTaxAmount,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.Status,
		&i.Notes,
		&i.Terms,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
		&i.DeletedAt,
	)
	return i, err
}

const updateEstimateTotals = `-- name: UpdateEstimateTotals :one
UPDATE estimate SET
    subtotal = $1, total_tax_amount = $2,
    total_amount = $3, updated_at = NOW()
WHERE id = $4 AND deleted_at IS NULL
    AND ($5::bigint IS NULL OR resource_version = $5)
RETURNING id, business_id, customer_id, estimate_number, estimate_date, expiration_date, subtotal, total_tax_amount, discount_amount, total_amount, status, notes, terms, created_by_user_id, created_at, updated_at, resource_version, deleted_at
`

type UpdateEstimateTotalsParams struct {
	Subtotal        pgtype.Numeric `json:"subtotal"`
	TotalTaxAmount  pgtype.Numeric `json:"total_tax_amount"`
	TotalAmount     pgtype.Numeric `json:"total_amount"`
	ID              int64          `json:"id"`
	ResourceVersion *int64         `json:"resource_version"`
}

// Carries the resource_version precondition for UpdateEstimateLineItems as a whole: it's
// the first statement in that transaction to touch the estimate row, so it both checks
// the version and takes the row lock everything after it (line-item replace) runs under.
func (q *Queries) UpdateEstimateTotals(ctx context.Context, arg UpdateEstimateTotalsParams) (Estimate, error) {
	row := q.db.QueryRow(ctx, updateEstimateTotals,
		arg.Subtotal,
		arg.TotalTaxAmount,
		arg.TotalAmount,
		arg.ID,
		arg.ResourceVersion,
	)
	var i Estimate
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CustomerID,
		&i.EstimateNumber,
		&i.EstimateDate,
		&i.ExpirationDate,
		&i.Subtotal,
		&i.TotalTaxAmount,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.Status,
		&i.Notes,
		&i.Terms,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
		&i.DeletedAt,
	)
	return i, err
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :one
UPDATE invoice SET status = $1, updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL
    AND ($3::bigint IS NULL OR resource_version = $3)
RETURNING id, business_id, contact_id, invoice_type, estimate_id, invoice_number, invoice_date, due_date, subtotal, total_tax_amount, discount_amount, total_amount, paid_amount, balance_due, status, notes, terms, ledger_transaction_id, created_by_user_id, created_at, updated_at, resource_version, deleted_at
`

type UpdateInvoiceStatusParams struct {
	Status          string `json:"status"`
	ID              int64  `json:"id"`
	ResourceVersion *int64 `json:"resource_version"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoiceStatus, arg.Status, arg.ID, arg.ResourceVersion)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ContactID,
		&i.InvoiceType,
		&i.EstimateID,
		&i.InvoiceNumber,
		&i.InvoiceDate,
		&i.DueDate,
		&i.Subtotal,
		&i.TotalTaxAmount,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.BalanceDue,
		&i.Status,
		&i.Notes,
		&i.Terms,
		&i.LedgerTransactionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
		&i.DeletedAt,
	)
	return i, err
}

const updateInvoiceTotals = `-- name: UpdateInvoiceTotals :one
UPDATE invoice SET
    subtotal = $1, total_tax_amount = $2,
    total_amount = $3, balance_due = $4, updated_at = NOW()
WHERE id = $5 AND deleted_at IS NULL
    AND ($6::bigint IS NULL OR resource_version = $6)
RETURNING id, business_id, contact_id, invoice_type, estimate_id, invoice_number, invoice_date, due_date, subtotal, total_tax_amount, discount_amount, total_amount, paid_amount, balance_due, status, notes, terms, ledger_transaction_id, created_by_user_id, created_at, updated_at, resource_version, deleted_at
`

type UpdateInvoiceTotalsParams struct {
	Subtotal        pgtype.Numeric `json:"subtotal"`
	TotalTaxAmount  pgtype.Numeric `json:"total_tax_amount"`
	TotalAmount     pgtype.Numeric `json:"total_amount"`
	BalanceDue      pgtype.Numeric `json:"balance_due"`
	ID              int64          `json:"id"`
	ResourceVersion *int64         `json:"resource_version"`
}

// Same role as UpdateEstimateTotals: the version check + row lock for UpdateInvoiceLineItems.
// SetInvoiceLedgerTransaction/ApplyPaymentToInvoice below stay unconditional - they run
// either later in this same transaction (lock already held) or as a side effect of another
// resource's write (a payment), where there's no client-held invoice version to check.
func (q *Queries) UpdateInvoiceTotals(ctx context.Context, arg UpdateInvoiceTotalsParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoiceTotals,
		arg.Subtotal,
		arg.TotalTaxAmount,
		arg.TotalAmount,
		arg.BalanceDue,
		arg.ID,
		arg.ResourceVersion,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ContactID,
		&i.InvoiceType,
		&i.EstimateID,
		&i.InvoiceNumber,
		&i.InvoiceDate,
		&i.DueDate,
		&i.Subtotal,
		&i.TotalTaxAmount,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.BalanceDue,
		&i.Status,
		&i.Notes,
		&i.Terms,
		&i.LedgerTransactionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
		&i.DeletedAt,
	)
	return i, err
}
